### ISSUE TITLE
ProtGctfRefine fails since a389fe8

### ISSUE THREAD

**Issue by yaizar** [scipion-em/scipion-em-gctf#8]
```
00001:   RUNNING PROTOCOL -----------------
00002:        HostName: nolan.cnb.csic.es
00003:             PID: 65242
00004:         Scipion: v2.0 (2018-12-19) Diocletian (devel-pluginization-fixes aab29ac)
00005:      currentDir: /home/buildbot-slave/data/slave/devel/ScipionUserData/projects/TestGctfRefine
00006:      workingDir: Runs/000206_ProtGctfRefine
00007:         runMode: Continue
00008:             MPI: 1
00009:         threads: 1
00010:   len(steps) 3 len(prevSteps) 0 
00011:    Starting at step: 1
00012:    Running steps 
00013:   STARTED: convertInputStep, step 1
00014:     2018-12-21 03:40:27.067276
00015:   Input File: Runs/000142_ProtImportMicrographs/extra/BPV_1386.mrc
00016:   Output File: Runs/000206_ProtGctfRefine/tmp/BPV_1386/BPV_1386.mrc
00017:   Input File: Runs/000142_ProtImportMicrographs/extra/BPV_1387.mrc
00018:   Output File: Runs/000206_ProtGctfRefine/tmp/BPV_1387/BPV_1387.mrc
00019:   Input File: Runs/000142_ProtImportMicrographs/extra/BPV_1388.mrc
00020:   Output File: Runs/000206_ProtGctfRefine/tmp/BPV_1388/BPV_1388.mrc
00021:   Scaling coordinates by a factor *4.00*
00022:   ** Running command: xmipp_transform_downsample -i Runs/000142_ProtImportMicrographs/extra/BPV_1386.mrc -o Runs/000206_ProtGctfRefine/tmp/BPV_1386/BPV_1386.mrc --step 2.000000 --method fourier
00023:   ** Running command: xmipp_transform_downsample -i Runs/000142_ProtImportMicrographs/extra/BPV_1387.mrc -o Runs/000206_ProtGctfRefine/tmp/BPV_1387/BPV_1387.mrc --step 2.000000 --method fourier
00024:   ** Running command: xmipp_transform_downsample -i Runs/000142_ProtImportMicrographs/extra/BPV_1388.mrc -o Runs/000206_ProtGctfRefine/tmp/BPV_1388/BPV_1388.mrc --step 2.000000 --method fourier
00025:   FINISHED: convertInputStep, step 1
00026:     2018-12-21 03:40:54.064577
00027:   STARTED: refineCtfStep, step 2
00028:     2018-12-21 03:40:54.164859
00029:   Traceback (most recent call last):
00030:     File "/home/buildbot-slave/data/slave/devel/scipion/pyworkflow/protocol/protocol.py", line 190, in run
00031:       self._run()
00032:     File "/home/buildbot-slave/data/slave/devel/scipion/pyworkflow/protocol/protocol.py", line 237, in _run
00033:       resultFiles = self._runFunc()
00034:     File "/home/buildbot-slave/data/slave/devel/scipion/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00035:       return self._func(*self._args)
00036:     File "/home/buildbot-slave/data/slave/devel/scipion/software/lib/python2.7/site-packages/gctf/protocols/protocol_gctf_refine.py", line 439, in refineCtfStep
00037:       self._prepareCommand()
00038:     File "/home/buildbot-slave/data/slave/devel/scipion/software/lib/python2.7/site-packages/gctf/protocols/protocol_gctf_refine.py", line 619, in _prepareCommand
00039:       self._argsGctf()
00040:     File "/home/buildbot-slave/data/slave/devel/scipion/software/lib/python2.7/site-packages/gctf/protocols/protocol_gctf_refine.py", line 636, in _argsGctf
00041:       self._args += "--gid %d " % self.GPUCore.get()
00042:   AttributeError: 'ProtGctfRefine' object has no attribute 'GPUCore'
00043:   Protocol failed: 'ProtGctfRefine' object has no attribute 'GPUCore'
00044:   FAILED: refineCtfStep, step 2
00045:     2018-12-21 03:40:54.229901
00046:   ------------------- PROTOCOL FAILED (DONE 2/3)
```

**Comment by azazellochg** [comment]
Thanks, @yaizar !
